name: split_spend
description: 'A new Flutter project.'

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.1.0
  dots_indicator: ^4.0.1

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  supabase_flutter: ^2.12.4
  dio: ^5.9.2
  fluttertoast: ^9.0.0
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/general/
    - assets/img/onboarding/page_one.png
    - assets/img/onboarding/page_two.png
    - assets/img/onboarding/page_three.png
    - assets/config/supabase.local.json
